### Escenario 1

In [111]:
import pandas as pd

In [112]:
# Definición del programa
def calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l):
    """
    Función para calcular distintos escenarios del proceso de lixiviación.
    """
    # Nombres de las materias primas
    materias_primas = ['Mg', 'Mn', 'Al', 'Zn', 'Fe']

    # Inicializar resultados
    resultados = []

    # Cálculos para cada materia prima
    for i, MPi_porcentaje in enumerate(Composicion):
        # Nombre de la materia prima
        MPi = materias_primas[i]

        # Cálculo de la cantidad de MPi en gramos
        MPi_g = MPi_porcentaje * MP / 100

        # Cálculo del residuo sólido seco
        Rsi = Cte3 * RSS_porcentajes[i] / 100

        # Cálculo de la eficacia (Base Sólida)
        eficacia_bs = round(((MPi_g - Rsi) / MPi_g)*100,2)

        # Cálculo de la eficacia (Base Líquida)
        eficacia_bl = round((((cte2_por_MP[i] * lixivliquido) + (lavado_l * MPiLL_g_l[i])) / MPi_g)*100,2)


        # Guardar resultados
        resultados.append({
            'Materia Prima': MPi,
            'MP(gr)': MPi_g,
            'Residuo (gr)': Rsi,
            'Eficacia (BS)': eficacia_bs,
            'Eficacia (BL)': eficacia_bl
        })

    # Crear un DataFrame para mostrar los resultados
    df_resultados = pd.DataFrame(resultados)
    return df_resultados

# Ejemplo de uso
if __name__ == "__main__":
    # Parámetros constantes
    MP = 50  # Cantidad total de material inicial en gramos
    pH = 0.5  # Valor de pH
    tiempo = 1  # Tiempo en horas
    temperatura = 40  # Temperatura en °C
    lixivliquido = 0.294  # Lixiviante en litros
    Cte3 = 22.6  # Residuo sólido seco en gramos
    lavado_l = 0.218 # Volumen Licor de lavado en litros

    # Parámetros variables
    Composicion = [2.46, 21.70,2.14, 15.40, 1.57]  # Porcentajes de materias primas
    RSS_porcentajes = [0.34,14.7,0.85,1.15,1.98]  # Porcentajes de residuos sólidos secos
    MPiLL_g_l = [0.448,3.29,0.603,4.66,0.212]  # MP en licor de lavado
    cte2_por_MP= [2.79,17.2,1.82,29.2,0.786] #cte2 (g/l)

   # Calcular resultados
resultados = calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2_por_MP, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l)
df_resultados = pd.DataFrame(resultados)

df_resultados.head(5)

  Materia Prima  MP(gr)  Residuo (gr)  Eficacia (BS)  Eficacia (BL)
0            Mg   1.230       0.07684          93.75          74.63
1            Mn  10.850       3.32220          69.38          53.22
2            Al   1.070       0.19210          82.05          62.29
3            Zn   7.700       0.25990          96.62         124.68
4            Fe   0.785       0.44748          43.00          35.32

In [113]:
new_columns = pd.DataFrame({
    'MP': [50,50,50,50,50],
    'Ph': [0.5, 0.5, 0.5,0.5,0.5],
    'Tiempo': [1,1,1,1,1,],
    'Temperatura': [40,40,40,40,40],
    'LixivLiqui': [0.294, 0.294, 0.294,0.294,0.294],
    'Cte3': [22.6,22.6,22.6,22.6,22.6],
    'LicorLavado': [0.218,0.218,0.218,0.218,0.218],
})

df = pd.concat([df_resultados,new_columns], axis=1)
df.head(5)

,Materia Prima,MP(gr),Residuo (gr),Eficacia (BS),Eficacia (BL),MP,Ph,Tiempo,Temperatura,LixivLiqui,Cte3,LicorLavado
0,Mg,1.230,0.07684,93.75,74.63,50,0.5,1,40,0.294,22.6,0.218
1,Mn,10.850,3.32220,69.38,53.22,50,0.5,1,40,0.294,22.6,0.218
2,Al,1.070,0.19210,82.05,62.29,50,0.5,1,40,0.294,22.6,0.218
3,Zn,7.700,0.25990,96.62,124.68,50,0.5,1,40,0.294,22.6,0.218
4,Fe,0.785,0.44748,43.00,35.32,50,0.5,1,40,0.294,22.6,0.218

### Escenario 2

In [114]:
# Definición del programa
def calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l):
    """
    Función para calcular distintos escenarios del proceso de lixiviación.
    """
    # Nombres de las materias primas
    materias_primas = ['Mg', 'Mn', 'Al', 'Zn', 'Fe']

    # Inicializar resultados
    resultados = []

    # Cálculos para cada materia prima
    for i, MPi_porcentaje in enumerate(Composicion):
        # Nombre de la materia prima
        MPi = materias_primas[i]

        # Cálculo de la cantidad de MPi en gramos
        MPi_g = MPi_porcentaje * MP / 100

        # Cálculo del residuo sólido seco
        Rsi = Cte3 * RSS_porcentajes[i] / 100

        # Cálculo de la eficacia (Base Sólida)
        eficacia_bs = round(((MPi_g - Rsi) / MPi_g)*100,2)

        # Cálculo de la eficacia (Base Líquida)
        eficacia_bl = round((((cte2_por_MP[i] * lixivliquido) + (lavado_l * MPiLL_g_l[i])) / MPi_g)*100,2)


        # Guardar resultados
        resultados.append({
            'Materia Prima': MPi,
            'MP(gr)': MPi_g,
            'Residuo (gr)': Rsi,
            'Eficacia (BS)': eficacia_bs,
            'Eficacia (BL)': eficacia_bl
        })

    # Crear un DataFrame para mostrar los resultados
    df_resultados = pd.DataFrame(resultados)
    return df_resultados

# Ejemplo de uso
if __name__ == "__main__":
    # Parámetros constantes
    MP = 50  # Cantidad total de material inicial en gramos
    pH = 0.5  # Valor de pH
    tiempo = 1  # Tiempo en horas
    temperatura = 60  # Temperatura en °C
    lixivliquido = 0.4  # Lixiviante en litros
    Cte3 = 21.2  # Residuo sólido seco en gramos
    lavado_l = 0.218 # Volumen Licor de lavado en litros

    # Parámetros variables
    Composicion = [2.46, 21.70,2.14, 15.40, 1.57]  # Porcentajes de materias primas
    RSS_porcentajes = [0.25,11.8,1.13,1.21,1.38]  # Porcentajes de residuos sólidos secos
    MPiLL_g_l = [0.406,2.82,0.535,4.15,0.181]  # Licor lavado (g/L)
    cte2_por_MP= [2.31,15.8,1.63,24.2,.949] #cte2 (g/l)

   # Calcular resultados
resultados2 = calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2_por_MP, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l)
df_resultados2 = pd.DataFrame(resultados2)

df_resultados2.head(5)

  Materia Prima  MP(gr)  Residuo (gr)  Eficacia (BS)  Eficacia (BL)
0            Mg   1.230       0.05300          95.69          82.32
1            Mn  10.850       2.50160          76.94          63.91
2            Al   1.070       0.23956          77.61          71.83
3            Zn   7.700       0.25652          96.67         137.46
4            Fe   0.785       0.29256          62.73          53.38

In [115]:
new_columns2 = pd.DataFrame({
    'MP': [50,50,50,50,50],
    'Ph': [0.5, 0.5, 0.5,0.5,0.5],
    'Tiempo': [1,1,1,1,1],
    'Temperatura':[ 60,60,60,60,60],
    'LixivLiqui': [0.4, 0.4, 0.4,0.4,0.4],
    'Cte3': [21.2,21.2,21.2,21.2,21.2],
    'LicorLavado': [0.218,0.218,0.218,0.218,0.218],
})

df2 = pd.concat([df_resultados2,new_columns2], axis=1)
df2.head(5)

,Materia Prima,MP(gr),Residuo (gr),Eficacia (BS),Eficacia (BL),MP,Ph,Tiempo,Temperatura,LixivLiqui,Cte3,LicorLavado
0,Mg,1.230,0.05300,95.69,82.32,50,0.5,1,60,0.4,21.2,0.218
1,Mn,10.850,2.50160,76.94,63.91,50,0.5,1,60,0.4,21.2,0.218
2,Al,1.070,0.23956,77.61,71.83,50,0.5,1,60,0.4,21.2,0.218
3,Zn,7.700,0.25652,96.67,137.46,50,0.5,1,60,0.4,21.2,0.218
4,Fe,0.785,0.29256,62.73,53.38,50,0.5,1,60,0.4,21.2,0.218

### Escenario 3

In [116]:
# Definición del programa
def calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l):
    """
    Función para calcular distintos escenarios del proceso de lixiviación.
    """
    # Nombres de las materias primas
    materias_primas = ['Mg', 'Mn', 'Al', 'Zn', 'Fe']

    # Inicializar resultados
    resultados = []

    # Cálculos para cada materia prima
    for i, MPi_porcentaje in enumerate(Composicion):
        # Nombre de la materia prima
        MPi = materias_primas[i]

        # Cálculo de la cantidad de MPi en gramos
        MPi_g = MPi_porcentaje * MP / 100

        # Cálculo del residuo sólido seco
        Rsi = Cte3 * RSS_porcentajes[i] / 100

        # Cálculo de la eficacia (Base Sólida)
        eficacia_bs = round(((MPi_g - Rsi) / MPi_g)*100,2)

        # Cálculo de la eficacia (Base Líquida)
        eficacia_bl = round((((cte2_por_MP[i] * lixivliquido) + (lavado_l * MPiLL_g_l[i])) / MPi_g)*100,2)


        # Guardar resultados
        resultados.append({
            'Materia Prima': MPi,
            'MP(gr)': MPi_g,
            'Residuo (gr)': Rsi,
            'Eficacia (BS)': eficacia_bs,
            'Eficacia (BL)': eficacia_bl
        })

    # Crear un DataFrame para mostrar los resultados
    df_resultados = pd.DataFrame(resultados)
    return df_resultados

# Ejemplo de uso
if __name__ == "__main__":
    # Parámetros constantes
    MP = 50  # Cantidad total de material inicial en gramos
    pH = 0.5  # Valor de pH
    tiempo = 2  # Tiempo en horas
    temperatura = 40  # Temperatura en °C
    lixivliquido = 0.4  # Lixiviante en litros
    Cte3 = 21.4  # Residuo sólido seco en gramos
    lavado_l = 0.198 # Volumen Licor de lavado en litros

    # Parámetros variables
    Composicion = [2.46, 21.70,2.14, 15.40, 1.57]  # Porcentajes de materias primas
    RSS_porcentajes = [0.22,13.70,0.74,0.85,2.04]  # Porcentajes de residuos sólidos secos
    MPiLL_g_l = [0.236,2.17,0.156,2.45,0.179]  # Licor lavado (g/L)
    cte2_por_MP= [2.27,14.2,1.57,22.4,0.885] #cte2 (g/l)

   # Calcular resultados
resultados3 = calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2_por_MP, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l)
df_resultados3 = pd.DataFrame(resultados3)

df_resultados3.head(5)

  Materia Prima  MP(gr)  Residuo (gr)  Eficacia (BS)  Eficacia (BL)
0            Mg   1.230       0.04708          96.17          77.62
1            Mn  10.850       2.93180          72.98          56.31
2            Al   1.070       0.15836          85.20          61.58
3            Zn   7.700       0.18190          97.64         122.66
4            Fe   0.785       0.43656          44.39          49.61

In [117]:
new_columns3 = pd.DataFrame({
    'MP': [50,50,50,50,50],
    'Ph': [0.5, 0.5, 0.5,0.5,0.5],
    'Tiempo': [2,2,2,2,2],
    'Temperatura':[ 40,40,40,40,40],
    'LixivLiqui': [0.4, 0.4, 0.4,0.4,0.4],
    'Cte3': [21.2,21.2,21.2,21.2,21.2],
    'LicorLavado': [0.218,0.218,0.218,0.218,0.218],
})

df3 = pd.concat([df_resultados3,new_columns3], axis=1)
df3.head(5)

,Materia Prima,MP(gr),Residuo (gr),Eficacia (BS),Eficacia (BL),MP,Ph,Tiempo,Temperatura,LixivLiqui,Cte3,LicorLavado
0,Mg,1.230,0.04708,96.17,77.62,50,0.5,2,40,0.4,21.2,0.218
1,Mn,10.850,2.93180,72.98,56.31,50,0.5,2,40,0.4,21.2,0.218
2,Al,1.070,0.15836,85.20,61.58,50,0.5,2,40,0.4,21.2,0.218
3,Zn,7.700,0.18190,97.64,122.66,50,0.5,2,40,0.4,21.2,0.218
4,Fe,0.785,0.43656,44.39,49.61,50,0.5,2,40,0.4,21.2,0.218

### Escenario 4

In [118]:
# Definición del programa
def calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l):
    """
    Función para calcular distintos escenarios del proceso de lixiviación.
    """
    # Nombres de las materias primas
    materias_primas = ['Mg', 'Mn', 'Al', 'Zn', 'Fe']

    # Inicializar resultados
    resultados = []

    # Cálculos para cada materia prima
    for i, MPi_porcentaje in enumerate(Composicion):
        # Nombre de la materia prima
        MPi = materias_primas[i]

        # Cálculo de la cantidad de MPi en gramos
        MPi_g = MPi_porcentaje * MP / 100

        # Cálculo del residuo sólido seco
        Rsi = Cte3 * RSS_porcentajes[i] / 100

        # Cálculo de la eficacia (Base Sólida)
        eficacia_bs = round(((MPi_g - Rsi) / MPi_g)*100,2)

        # Cálculo de la eficacia (Base Líquida)
        eficacia_bl = round((((cte2_por_MP[i] * lixivliquido) + (lavado_l * MPiLL_g_l[i])) / MPi_g)*100,2)


        # Guardar resultados
        resultados.append({
            'Materia Prima': MPi,
            'MP(gr)': MPi_g,
            'Residuo (gr)': Rsi,
            'Eficacia (BS)': eficacia_bs,
            'Eficacia (BL)': eficacia_bl
        })

    # Crear un DataFrame para mostrar los resultados
    df_resultados = pd.DataFrame(resultados)
    return df_resultados

# Ejemplo de uso
if __name__ == "__main__":
    # Parámetros constantes
    MP = 50  # Cantidad total de material inicial en gramos
    pH = 0.5  # Valor de pH
    tiempo = 2  # Tiempo en horas
    temperatura = 40  # Temperatura en °C
    lixivliquido = 0.335  # Lixiviante en litros
    Cte3 = 20.8  # Residuo sólido seco en gramos
    lavado_l = 0.205 # Voulmen Licor de lavado en litros

    # Parámetros variables
    Composicion = [2.46, 21.70,2.14, 15.40, 1.57]  # Porcentajes de materias primas
    RSS_porcentajes = [0.31,17.8,0.91,1.17,2.44]  # Porcentajes de residuos sólidos secos
    MPiLL_g_l = [0.288,2.13,0.172,3.08,0.194]  # Licor lavado (g/L)
    cte2_por_MP= [2.76,17.6,1.82,30,0.634] #cte2 (g/l)

   # Calcular resultados
resultados4 = calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2_por_MP, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l)
df_resultados4 = pd.DataFrame(resultados4)

df_resultados4.head(5)

  Materia Prima  MP(gr)  Residuo (gr)  Eficacia (BS)  Eficacia (BL)
0            Mg   1.230       0.06448          94.76          79.97
1            Mn  10.850       3.70240          65.88          58.37
2            Al   1.070       0.18928          82.31          60.28
3            Zn   7.700       0.24336          96.84         138.72
4            Fe   0.785       0.50752          35.35          32.12

In [119]:
new_columns4 = pd.DataFrame({
    'MP': [50,50,50,50,50],
    'Ph': [0.5, 0.5, 0.5,0.5,0.5],
    'Tiempo': [2,2,2,2,2],
    'Temperatura':[ 40,40,40,40,40],
    'LixivLiqui': [0.4, 0.4, 0.4,0.4,0.4],
    'Cte3': [20.8,20.8,20.8,20.8,20.8],
    'LicorLavado': [0.335,0.335,0.335,0.335,0.335],
})

df4 = pd.concat([df_resultados4,new_columns4], axis=1)
df4.head(5)

,Materia Prima,MP(gr),Residuo (gr),Eficacia (BS),Eficacia (BL),MP,Ph,Tiempo,Temperatura,LixivLiqui,Cte3,LicorLavado
0,Mg,1.230,0.06448,94.76,79.97,50,0.5,2,40,0.4,20.8,0.335
1,Mn,10.850,3.70240,65.88,58.37,50,0.5,2,40,0.4,20.8,0.335
2,Al,1.070,0.18928,82.31,60.28,50,0.5,2,40,0.4,20.8,0.335
3,Zn,7.700,0.24336,96.84,138.72,50,0.5,2,40,0.4,20.8,0.335
4,Fe,0.785,0.50752,35.35,32.12,50,0.5,2,40,0.4,20.8,0.335

### Escenario 5

In [120]:
# Definición del programa
def calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l):
    """
    Función para calcular distintos escenarios del proceso de lixiviación.
    """
    # Nombres de las materias primas
    materias_primas = ['Mg', 'Mn', 'Al', 'Zn', 'Fe']

    # Inicializar resultados
    resultados = []

    # Cálculos para cada materia prima
    for i, MPi_porcentaje in enumerate(Composicion):
        # Nombre de la materia prima
        MPi = materias_primas[i]

        # Cálculo de la cantidad de MPi en gramos
        MPi_g = MPi_porcentaje * MP / 100

        # Cálculo del residuo sólido seco
        Rsi = Cte3 * RSS_porcentajes[i] / 100

        # Cálculo de la eficacia (Base Sólida)
        eficacia_bs = round(((MPi_g - Rsi) / MPi_g)*100,2)

        # Cálculo de la eficacia (Base Líquida)
        eficacia_bl = round((((cte2_por_MP[i] * lixivliquido) + (lavado_l * MPiLL_g_l[i])) / MPi_g)*100,2)


        # Guardar resultados
        resultados.append({
            'Materia Prima': MPi,
            'MP(gr)': MPi_g,
            'Residuo (gr)': Rsi,
            'Eficacia (BS)': eficacia_bs,
            'Eficacia (BL)': eficacia_bl
        })

    # Crear un DataFrame para mostrar los resultados
    df_resultados = pd.DataFrame(resultados)
    return df_resultados

# Ejemplo de uso
if __name__ == "__main__":
    # Parámetros constantes
    MP = 50  # Cantidad total de material inicial en gramos
    pH = 0.5  # Valor de pH
    tiempo = 2  # Tiempo en horas
    temperatura = 60  # Temperatura en °C
    lixivliquido = 0.222  # Lixiviante en litros
    Cte3 = 21.3  # Residuo sólido seco en gramos
    lavado_l = 0.19 # VolumenLicor de lavado en litros

    # Parámetros variables
    Composicion = [2.46, 21.70,2.14, 15.40, 1.57]  # Porcentajes de materias primas
    RSS_porcentajes = [0.19,12,0.63,0.52,1.47]  # Porcentajes de residuos sólidos secos
    MPiLL_g_l = [0.843,5.69,0.523,8.13,0.35]  # Licor lavado (g/L)
    cte2_por_MP= [4.54,27.2,2.96,36.1,1.41] #cte2 (g/l)

   # Calcular resultados
resultados5 = calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2_por_MP, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l)
df_resultados5 = pd.DataFrame(resultados5)

df_resultados5.head(5)

  Materia Prima  MP(gr)  Residuo (gr)  Eficacia (BS)  Eficacia (BL)
0            Mg   1.230       0.04047          96.71          94.96
1            Mn  10.850       2.55600          76.44          65.62
2            Al   1.070       0.13419          87.46          70.70
3            Zn   7.700       0.11076          98.56         124.14
4            Fe   0.785       0.31311          60.11          48.35

In [121]:
new_columns5 = pd.DataFrame({
    'MP': [50,50,50,50,50],
    'Ph': [0.5, 0.5, 0.5,0.5,0.5],
    'Tiempo': [2,2,2,2,2],
    'Temperatura':[ 60,60,60,60,60],
    'LixivLiqui': [0.222,0.222,0.222,0.222,0.222],
    'Cte3': [21.3,21.3,21.3,21.3,21.3],
    'LicorLavado': [0.335,0.335,0.335,0.335,0.335],
})

df5 = pd.concat([df_resultados5,new_columns5], axis=1)
df5.head(5)

,Materia Prima,MP(gr),Residuo (gr),Eficacia (BS),Eficacia (BL),MP,Ph,Tiempo,Temperatura,LixivLiqui,Cte3,LicorLavado
0,Mg,1.230,0.04047,96.71,94.96,50,0.5,2,60,0.222,21.3,0.335
1,Mn,10.850,2.55600,76.44,65.62,50,0.5,2,60,0.222,21.3,0.335
2,Al,1.070,0.13419,87.46,70.70,50,0.5,2,60,0.222,21.3,0.335
3,Zn,7.700,0.11076,98.56,124.14,50,0.5,2,60,0.222,21.3,0.335
4,Fe,0.785,0.31311,60.11,48.35,50,0.5,2,60,0.222,21.3,0.335

### Escenario 6

In [122]:
# Definición del programa
def calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l):
    """
    Función para calcular distintos escenarios del proceso de lixiviación.
    """
    # Nombres de las materias primas
    materias_primas = ['Mg', 'Mn', 'Al', 'Zn', 'Fe']

    # Inicializar resultados
    resultados = []

    # Cálculos para cada materia prima
    for i, MPi_porcentaje in enumerate(Composicion):
        # Nombre de la materia prima
        MPi = materias_primas[i]

        # Cálculo de la cantidad de MPi en gramos
        MPi_g = MPi_porcentaje * MP / 100

        # Cálculo del residuo sólido seco
        Rsi = Cte3 * RSS_porcentajes[i] / 100

        # Cálculo de la eficacia (Base Sólida)
        eficacia_bs = round(((MPi_g - Rsi) / MPi_g)*100,2)

        # Cálculo de la eficacia (Base Líquida)
        eficacia_bl = round((((cte2_por_MP[i] * lixivliquido) + (lavado_l * MPiLL_g_l[i])) / MPi_g)*100,2)


        # Guardar resultados
        resultados.append({
            'Materia Prima': MPi,
            'MP(gr)': MPi_g,
            'Residuo (gr)': Rsi,
            'Eficacia (BS)': eficacia_bs,
            'Eficacia (BL)': eficacia_bl
        })

    # Crear un DataFrame para mostrar los resultados
    df_resultados = pd.DataFrame(resultados)
    return df_resultados

# Ejemplo de uso
if __name__ == "__main__":
    # Parámetros constantes
    MP = 50  # Cantidad total de material inicial en gramos
    pH = 1  # Valor de pH
    tiempo = 1  # Tiempo en horas
    temperatura = 40  # Temperatura en °C
    lixivliquido = 0.262  # Lixiviante en litros
    Cte3 = 23.9  # Residuo sólido seco en gramos
    lavado_l = 0.202 # Volumen Licor de lavado en litros

    # Parámetros variables
    Composicion = [2.46, 21.70,2.14, 15.40, 1.57]  # Porcentajes de materias primas
    RSS_porcentajes = [0.27,15.9,1.32,0.8,2.26]  # Porcentajes de residuos sólidos secos
    MPiLL_g_l = [0.701,4.84,0.435,4.92,0.312]  # Licor lavado (g/L)
    cte2_por_MP= [4.2,22.8,2.54,26.7,0.741] #cte2 (g/l)

   # Calcular resultados
resultados6 = calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2_por_MP, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l)
df_resultados6 = pd.DataFrame(resultados6)

df_resultados6.head(5)

  Materia Prima  MP(gr)  Residuo (gr)  Eficacia (BS)  Eficacia (BL)
0            Mg   1.230       0.06453          94.75         100.98
1            Mn  10.850       3.80010          64.98          64.07
2            Al   1.070       0.31548          70.52          70.41
3            Zn   7.700       0.19120          97.52         103.76
4            Fe   0.785       0.54014          31.19          32.76

In [123]:
new_columns6 = pd.DataFrame({
    'MP': [50,50,50,50,50],
    'Ph': [1,1,1,1,1],
    'Tiempo': [1,1,1,1,1],
    'Temperatura':[ 40,40,40,40,40],
    'LixivLiqui': [0.262,0.262,0.262,0.262,0.262],
    'Cte3': [23.9,23.9,23.9,23.9,23.9],
    'LicorLavado': [0.202,0.202,0.202,0.202,0.202],
})

df6 = pd.concat([df_resultados6,new_columns6], axis=1)
df6.head(5)

,Materia Prima,MP(gr),Residuo (gr),Eficacia (BS),Eficacia (BL),MP,Ph,Tiempo,Temperatura,LixivLiqui,Cte3,LicorLavado
0,Mg,1.230,0.06453,94.75,100.98,50,1,1,40,0.262,23.9,0.202
1,Mn,10.850,3.80010,64.98,64.07,50,1,1,40,0.262,23.9,0.202
2,Al,1.070,0.31548,70.52,70.41,50,1,1,40,0.262,23.9,0.202
3,Zn,7.700,0.19120,97.52,103.76,50,1,1,40,0.262,23.9,0.202
4,Fe,0.785,0.54014,31.19,32.76,50,1,1,40,0.262,23.9,0.202

### Escenario 7

In [124]:
# Definición del programa
def calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l):
    """
    Función para calcular distintos escenarios del proceso de lixiviación.
    """
    # Nombres de las materias primas
    materias_primas = ['Mg', 'Mn', 'Al', 'Zn', 'Fe']

    # Inicializar resultados
    resultados = []

    # Cálculos para cada materia prima
    for i, MPi_porcentaje in enumerate(Composicion):
        # Nombre de la materia prima
        MPi = materias_primas[i]

        # Cálculo de la cantidad de MPi en gramos
        MPi_g = MPi_porcentaje * MP / 100

        # Cálculo del residuo sólido seco
        Rsi = Cte3 * RSS_porcentajes[i] / 100

        # Cálculo de la eficacia (Base Sólida)
        eficacia_bs = round(((MPi_g - Rsi) / MPi_g)*100,2)

        # Cálculo de la eficacia (Base Líquida)
        eficacia_bl = round((((cte2_por_MP[i] * lixivliquido) + (lavado_l * MPiLL_g_l[i])) / MPi_g)*100,2)


        # Guardar resultados
        resultados.append({
            'Materia Prima': MPi,
            'MP(gr)': MPi_g,
            'Residuo (gr)': Rsi,
            'Eficacia (BS)': eficacia_bs,
            'Eficacia (BL)': eficacia_bl
        })

    # Crear un DataFrame para mostrar los resultados
    df_resultados = pd.DataFrame(resultados)
    return df_resultados

# Ejemplo de uso
if __name__ == "__main__":
    # Parámetros constantes
    MP = 50  # Cantidad total de material inicial en gramos
    pH = 1  # Valor de pH
    tiempo = 1  # Tiempo en horas
    temperatura = 60  # Temperatura en °C
    lixivliquido = 0.33  # Lixiviante en litros
    Cte3 = 21.7  # Residuo sólido seco en gramos
    lavado_l = 0.206 # Volumen Licor de lavado en litros

    # Parámetros variables
    Composicion = [2.46, 21.70,2.14, 15.40, 1.57]  # Porcentajes de materias primas
    RSS_porcentajes = [0.28,15.8,0.98,0.84,2.12]  # Porcentajes de residuos sólidos secos
    MPiLL_g_l = [0.369,2.4,0.209,2.93,0.149]  # Licor lavado (g/L)
    cte2_por_MP= [3.43,20.4,2.17,27.2,0.791] #cte2 (g/l)

   # Calcular resultados
resultados7 = calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2_por_MP, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l)
df_resultados7 = pd.DataFrame(resultados7)

df_resultados7.head(5)

  Materia Prima  MP(gr)  Residuo (gr)  Eficacia (BS)  Eficacia (BL)
0            Mg   1.230       0.06076          95.06          98.20
1            Mn  10.850       3.42860          68.40          66.60
2            Al   1.070       0.21266          80.13          70.95
3            Zn   7.700       0.18228          97.63         124.41
4            Fe   0.785       0.46004          41.40          37.16

In [125]:
new_columns7 = pd.DataFrame({
    'MP': [50,50,50,50,50],
    'Ph': [1,1,1,1,1],
    'Tiempo': [1,1,1,1,1],
    'Temperatura':[ 60,60,60,60,60],
    'LixivLiqui': [0.33,0.33,0.33,0.33,0.33],
    'Cte3': [21.7,21.7,21.7,21.7,21.7],
    'LicorLavado': [ 0.206, 0.206, 0.206, 0.206,0.206],
})

df7 = pd.concat([df_resultados7,new_columns7], axis=1)
df7.head(5)

,Materia Prima,MP(gr),Residuo (gr),Eficacia (BS),Eficacia (BL),MP,Ph,Tiempo,Temperatura,LixivLiqui,Cte3,LicorLavado
0,Mg,1.230,0.06076,95.06,98.20,50,1,1,60,0.33,21.7,0.206
1,Mn,10.850,3.42860,68.40,66.60,50,1,1,60,0.33,21.7,0.206
2,Al,1.070,0.21266,80.13,70.95,50,1,1,60,0.33,21.7,0.206
3,Zn,7.700,0.18228,97.63,124.41,50,1,1,60,0.33,21.7,0.206
4,Fe,0.785,0.46004,41.40,37.16,50,1,1,60,0.33,21.7,0.206

### Escenario 8

In [126]:
# Definición del programa
def calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l):
    """
    Función para calcular distintos escenarios del proceso de lixiviación.
    """
    # Nombres de las materias primas
    materias_primas = ['Mg', 'Mn', 'Al', 'Zn', 'Fe']

    # Inicializar resultados
    resultados = []

    # Cálculos para cada materia prima
    for i, MPi_porcentaje in enumerate(Composicion):
        # Nombre de la materia prima
        MPi = materias_primas[i]

        # Cálculo de la cantidad de MPi en gramos
        MPi_g = MPi_porcentaje * MP / 100

        # Cálculo del residuo sólido seco
        Rsi = Cte3 * RSS_porcentajes[i] / 100

        # Cálculo de la eficacia (Base Sólida)
        eficacia_bs = round(((MPi_g - Rsi) / MPi_g)*100,2)

        # Cálculo de la eficacia (Base Líquida)
        eficacia_bl = round((((cte2_por_MP[i] * lixivliquido) + (lavado_l * MPiLL_g_l[i])) / MPi_g)*100,2)


        # Guardar resultados
        resultados.append({
            'Materia Prima': MPi,
            'MP(gr)': MPi_g,
            'Residuo (gr)': Rsi,
            'Eficacia (BS)': eficacia_bs,
            'Eficacia (BL)': eficacia_bl
        })

    # Crear un DataFrame para mostrar los resultados
    df_resultados = pd.DataFrame(resultados)
    return df_resultados

# Ejemplo de uso
if __name__ == "__main__":
    # Parámetros constantes
    MP = 50  # Cantidad total de material inicial en gramos
    pH = 1  # Valor de pH
    tiempo = 2  # Tiempo en horas
    temperatura = 40  # Temperatura en °C
    lixivliquido = 0.348  # Lixiviante en litros
    Cte3 = 21.9  # Residuo sólido seco en gramos
    lavado_l = 0.194 # Volumen Licor de lavado en litros

    # Parámetros variables
    Composicion = [2.46, 21.70,2.14, 15.40, 1.57]  # Porcentajes de materias primas
    RSS_porcentajes = [0.30,18.5,0.96,1.08,2.57]  # Porcentajes de residuos sólidos secos
    MPiLL_g_l = [0.211,1.71,0.129,2.13,0.106]  # Licor lavado (g/L)
    cte2_por_MP= [3.17,18.9,1.89,28.6,0.541] #cte2 (g/l)

   # Calcular resultados
resultados8 = calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2_por_MP, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l)
df_resultados8 = pd.DataFrame(resultados8)

df_resultados8.head(5)

  Materia Prima  MP(gr)  Residuo (gr)  Eficacia (BS)  Eficacia (BL)
0            Mg   1.230       0.06570          94.66          93.02
1            Mn  10.850       4.05150          62.66          63.68
2            Al   1.070       0.21024          80.35          63.81
3            Zn   7.700       0.23652          96.93         134.62
4            Fe   0.785       0.56283          28.30          26.60

In [127]:
new_columns8 = pd.DataFrame({
    'MP': [50,50,50,50,50],
    'Ph': [1,1,1,1,1],
    'Tiempo': [2,2,2,2,2],
    'Temperatura':[ 40,40,40,40,40],
    'LixivLiqui': [ 0.348,0.348,0.348,0.348,0.348],
    'Cte3': [21.9,21.9,21.9,21.9,21.9],
    'LicorLavado': [0.194,0.194,0.194,0.194,0.194],
})

df8 = pd.concat([df_resultados8,new_columns8], axis=1)
df8.head(5)

,Materia Prima,MP(gr),Residuo (gr),Eficacia (BS),Eficacia (BL),MP,Ph,Tiempo,Temperatura,LixivLiqui,Cte3,LicorLavado
0,Mg,1.230,0.06570,94.66,93.02,50,1,2,40,0.348,21.9,0.194
1,Mn,10.850,4.05150,62.66,63.68,50,1,2,40,0.348,21.9,0.194
2,Al,1.070,0.21024,80.35,63.81,50,1,2,40,0.348,21.9,0.194
3,Zn,7.700,0.23652,96.93,134.62,50,1,2,40,0.348,21.9,0.194
4,Fe,0.785,0.56283,28.30,26.60,50,1,2,40,0.348,21.9,0.194

### Escenario 9

In [128]:
# Definición del programa
def calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l):
    """
    Función para calcular distintos escenarios del proceso de lixiviación.
    """
    # Nombres de las materias primas
    materias_primas = ['Mg', 'Mn', 'Al', 'Zn', 'Fe']

    # Inicializar resultados
    resultados = []

    # Cálculos para cada materia prima
    for i, MPi_porcentaje in enumerate(Composicion):
        # Nombre de la materia prima
        MPi = materias_primas[i]

        # Cálculo de la cantidad de MPi en gramos
        MPi_g = MPi_porcentaje * MP / 100

        # Cálculo del residuo sólido seco
        Rsi = Cte3 * RSS_porcentajes[i] / 100

        # Cálculo de la eficacia (Base Sólida)
        eficacia_bs = round(((MPi_g - Rsi) / MPi_g)*100,2)

        # Cálculo de la eficacia (Base Líquida)
        eficacia_bl = round((((cte2_por_MP[i] * lixivliquido) + (lavado_l * MPiLL_g_l[i])) / MPi_g)*100,2)


        # Guardar resultados
        resultados.append({
            'Materia Prima': MPi,
            'MP(gr)': MPi_g,
            'Residuo (gr)': Rsi,
            'Eficacia (BS)': eficacia_bs,
            'Eficacia (BL)': eficacia_bl
        })

    # Crear un DataFrame para mostrar los resultados
    df_resultados = pd.DataFrame(resultados)
    return df_resultados

# Ejemplo de uso
if __name__ == "__main__":
    # Parámetros constantes
    MP = 50  # Cantidad total de material inicial en gramos
    pH = 1  # Valor de pH
    tiempo = 2  # Tiempo en horas
    temperatura = 60  # Temperatura en °C
    lixivliquido = 0.215  # Lixiviante en litros
    Cte3 = 18.9  # Residuo sólido seco en gramos
    lavado_l = 0.19 # Volumen Licor de lavado en litros

    # Parámetros variables
    Composicion = [2.46, 21.70,2.14, 15.40, 1.57]  # Porcentajes de materias primas
    RSS_porcentajes = [0.25,14.5,0.8,1.17,2.4]  # Porcentajes de residuos sólidos secos
    MPiLL_g_l = [0.571,14.06,0.406,6.78,0.282]  # Licor lavado (g/L)
    cte2_por_MP= [3.57,25.8,2.55,40.5,1.15] #cte2 (g/l)

   # Calcular resultados
resultados9 = calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2_por_MP, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l)
df_resultados9 = pd.DataFrame(resultados9)

df_resultados9.head(5)

  Materia Prima  MP(gr)  Residuo (gr)  Eficacia (BS)  Eficacia (BL)
0            Mg   1.230       0.04725          96.16          71.22
1            Mn  10.850       2.74050          74.74          75.75
2            Al   1.070       0.15120          85.87          58.45
3            Zn   7.700       0.22113          97.13         129.81
4            Fe   0.785       0.45360          42.22          38.32

In [129]:
new_columns9 = pd.DataFrame({
    'MP': [50,50,50,50,50],
    'Ph': [1,1,1,1,1],
    'Tiempo': [2,2,2,2,2],
    'Temperatura':[60,60,60,60,60],
    'LixivLiqui': [0.215,0.215,0.215,0.215,0.215],
    'Cte3': [18.9,18.9,18.9,18.9,18.9],
    'LicorLavado': [0.19,0.19,0.19,0.19,0.19],
})

df9 = pd.concat([df_resultados9,new_columns9], axis=1)
df9.head(5)

,Materia Prima,MP(gr),Residuo (gr),Eficacia (BS),Eficacia (BL),MP,Ph,Tiempo,Temperatura,LixivLiqui,Cte3,LicorLavado
0,Mg,1.230,0.04725,96.16,71.22,50,1,2,60,0.215,18.9,0.19
1,Mn,10.850,2.74050,74.74,75.75,50,1,2,60,0.215,18.9,0.19
2,Al,1.070,0.15120,85.87,58.45,50,1,2,60,0.215,18.9,0.19
3,Zn,7.700,0.22113,97.13,129.81,50,1,2,60,0.215,18.9,0.19
4,Fe,0.785,0.45360,42.22,38.32,50,1,2,60,0.215,18.9,0.19

### Escenario 10

In [130]:
# Definición del programa
def calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l):
    """
    Función para calcular distintos escenarios del proceso de lixiviación.
    """
    # Nombres de las materias primas
    materias_primas = ['Mg', 'Mn', 'Al', 'Zn', 'Fe']

    # Inicializar resultados
    resultados = []

    # Cálculos para cada materia prima
    for i, MPi_porcentaje in enumerate(Composicion):
        # Nombre de la materia prima
        MPi = materias_primas[i]

        # Cálculo de la cantidad de MPi en gramos
        MPi_g = MPi_porcentaje * MP / 100

        # Cálculo del residuo sólido seco
        Rsi = Cte3 * RSS_porcentajes[i] / 100

        # Cálculo de la eficacia (Base Sólida)
        eficacia_bs = round(((MPi_g - Rsi) / MPi_g)*100,2)

        # Cálculo de la eficacia (Base Líquida)
        eficacia_bl = round((((cte2_por_MP[i] * lixivliquido) + (lavado_l * MPiLL_g_l[i])) / MPi_g)*100,2)


        # Guardar resultados
        resultados.append({
            'Materia Prima': MPi,
            'MP(gr)': MPi_g,
            'Residuo (gr)': Rsi,
            'Eficacia (BS)': eficacia_bs,
            'Eficacia (BL)': eficacia_bl
        })

    # Crear un DataFrame para mostrar los resultados
    df_resultados = pd.DataFrame(resultados)
    return df_resultados

# Ejemplo de uso
if __name__ == "__main__":
    # Parámetros constantes
    MP = 50  # Cantidad total de material inicial en gramos
    pH = 2  # Valor de pH
    tiempo = 1  # Tiempo en horas
    temperatura = 40  # Temperatura en °C
    lixivliquido = 0.242  # Lixiviante en litros
    Cte3 = 24.5  # Residuo sólido seco en gramos
    lavado_l = 0.194 # Volumen Licor de lavado en litros

    # Parámetros variables
    Composicion = [2.46, 21.70,2.14, 15.40, 1.57]  # Porcentajes de materias primas
    RSS_porcentajes = [0.81,21.8,1.16,3.92,2.97]  # Porcentajes de residuos sólidos secos
    MPiLL_g_l = [0.615,3.3,0.365,6.21,0.014]  # Licor lavado (g/L)
    cte2_por_MP= [3.39,17.9,2.01,35.5,0.111] #cte2 (g/l)

   # Calcular resultados
resultados10 = calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2_por_MP, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l)
df_resultados10 = pd.DataFrame(resultados10)

df_resultados10.head(5)

  Materia Prima  MP(gr)  Residuo (gr)  Eficacia (BS)  Eficacia (BL)
0            Mg   1.230       0.19845          83.87          76.40
1            Mn  10.850       5.34100          50.77          45.82
2            Al   1.070       0.28420          73.44          52.08
3            Zn   7.700       0.96040          87.53         127.22
4            Fe   0.785       0.72765           7.31           3.77

In [131]:
new_columns10 = pd.DataFrame({
    'MP': [50,50,50,50,50],
    'Ph': [2,2,2,2,2],
    'Tiempo': [1,1,1,1,1],
    'Temperatura':[40,40,40,40,40],
    'LixivLiqui': [0.242,0.242,0.242,0.242,0.242],
    'Cte3': [24.5,24.5,24.5,24.5,24.5],
    'LicorLavado': [ 0.194, 0.194, 0.194, 0.194, 0.194],
})

df10 = pd.concat([df_resultados10,new_columns10], axis=1)
df10.head(5)

,Materia Prima,MP(gr),Residuo (gr),Eficacia (BS),Eficacia (BL),MP,Ph,Tiempo,Temperatura,LixivLiqui,Cte3,LicorLavado
0,Mg,1.230,0.19845,83.87,76.40,50,2,1,40,0.242,24.5,0.194
1,Mn,10.850,5.34100,50.77,45.82,50,2,1,40,0.242,24.5,0.194
2,Al,1.070,0.28420,73.44,52.08,50,2,1,40,0.242,24.5,0.194
3,Zn,7.700,0.96040,87.53,127.22,50,2,1,40,0.242,24.5,0.194
4,Fe,0.785,0.72765,7.31,3.77,50,2,1,40,0.242,24.5,0.194

### Escenario 11

In [132]:
# Definición del programa
def calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l):
    """
    Función para calcular distintos escenarios del proceso de lixiviación.
    """
    # Nombres de las materias primas
    materias_primas = ['Mg', 'Mn', 'Al', 'Zn', 'Fe']

    # Inicializar resultados
    resultados = []

    # Cálculos para cada materia prima
    for i, MPi_porcentaje in enumerate(Composicion):
        # Nombre de la materia prima
        MPi = materias_primas[i]

        # Cálculo de la cantidad de MPi en gramos
        MPi_g = MPi_porcentaje * MP / 100

        # Cálculo del residuo sólido seco
        Rsi = Cte3 * RSS_porcentajes[i] / 100

        # Cálculo de la eficacia (Base Sólida)
        eficacia_bs = round(((MPi_g - Rsi) / MPi_g)*100,2)

        # Cálculo de la eficacia (Base Líquida)
        eficacia_bl = round((((cte2_por_MP[i] * lixivliquido) + (lavado_l * MPiLL_g_l[i])) / MPi_g)*100,2)


        # Guardar resultados
        resultados.append({
            'Materia Prima': MPi,
            'MP(gr)': MPi_g,
            'Residuo (gr)': Rsi,
            'Eficacia (BS)': eficacia_bs,
            'Eficacia (BL)': eficacia_bl
        })

    # Crear un DataFrame para mostrar los resultados
    df_resultados = pd.DataFrame(resultados)
    return df_resultados

# Ejemplo de uso
if __name__ == "__main__":
    # Parámetros constantes
    MP = 50  # Cantidad total de material inicial en gramos
    pH = 2  # Valor de pH
    tiempo = 1  # Tiempo en horas
    temperatura = 60  # Temperatura en °C
    lixivliquido = 0.205  # Lixiviante en litros
    Cte3 = 30.2  # Residuo sólido seco en gramos
    lavado_l = 0.1980 # Volumen Licor de lavado en litros

    # Parámetros variables
    Composicion = [2.46, 21.70,2.14, 15.40, 1.57]  # Porcentajes de materias primas
    RSS_porcentajes = [0.84,17.7,1.00,4.91,2.49]  # Porcentajes de residuos sólidos secos
    MPiLL_g_l = [0.433,2.5,0.304,3.64,0.022]  # Licor lavado (g/L)
    cte2_por_MP= [4.33,21.9,2.33,40,0.042] #cte2 (g/l)

   # Calcular resultados
resultados11 = calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2_por_MP, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l)
df_resultados11 = pd.DataFrame(resultados11)

df_resultados11.head(5)

  Materia Prima  MP(gr)  Residuo (gr)  Eficacia (BS)  Eficacia (BL)
0            Mg   1.230       0.25368          79.38          79.14
1            Mn  10.850       5.34540          50.73          45.94
2            Al   1.070       0.30200          71.78          50.27
3            Zn   7.700       1.48282          80.74         115.85
4            Fe   0.785       0.75198           4.21           1.65

In [133]:
new_columns11 = pd.DataFrame({
    'MP': [50,50,50,50,50],
    'Ph': [2,2,2,2,2],
    'Tiempo': [1,1,1,1,1],
    'Temperatura':[60,60,60,60,60],
    'LixivLiqui': [0.205,0.205,0.205,0.205,0.205],
    'Cte3': [30.2,30.2,30.2,30.2,30.2],
    'LicorLavado': [ 0.1980, 0.1980, 0.1980, 0.1980, 0.1980],
})

df11 = pd.concat([df_resultados11,new_columns11], axis=1)
df11.head(5)

,Materia Prima,MP(gr),Residuo (gr),Eficacia (BS),Eficacia (BL),MP,Ph,Tiempo,Temperatura,LixivLiqui,Cte3,LicorLavado
0,Mg,1.230,0.25368,79.38,79.14,50,2,1,60,0.205,30.2,0.198
1,Mn,10.850,5.34540,50.73,45.94,50,2,1,60,0.205,30.2,0.198
2,Al,1.070,0.30200,71.78,50.27,50,2,1,60,0.205,30.2,0.198
3,Zn,7.700,1.48282,80.74,115.85,50,2,1,60,0.205,30.2,0.198
4,Fe,0.785,0.75198,4.21,1.65,50,2,1,60,0.205,30.2,0.198

### Escenario 12

In [134]:
# Definición del programa
def calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l):
    """
    Función para calcular distintos escenarios del proceso de lixiviación.
    """
    # Nombres de las materias primas
    materias_primas = ['Mg', 'Mn', 'Al', 'Zn', 'Fe']

    # Inicializar resultados
    resultados = []

    # Cálculos para cada materia prima
    for i, MPi_porcentaje in enumerate(Composicion):
        # Nombre de la materia prima
        MPi = materias_primas[i]

        # Cálculo de la cantidad de MPi en gramos
        MPi_g = MPi_porcentaje * MP / 100

        # Cálculo del residuo sólido seco
        Rsi = Cte3 * RSS_porcentajes[i] / 100

        # Cálculo de la eficacia (Base Sólida)
        eficacia_bs = round(((MPi_g - Rsi) / MPi_g)*100,2)

        # Cálculo de la eficacia (Base Líquida)
        eficacia_bl = round((((cte2_por_MP[i] * lixivliquido) + (lavado_l * MPiLL_g_l[i])) / MPi_g)*100,2)


        # Guardar resultados
        resultados.append({
            'Materia Prima': MPi,
            'MP(gr)': MPi_g,
            'Residuo (gr)': Rsi,
            'Eficacia (BS)': eficacia_bs,
            'Eficacia (BL)': eficacia_bl
        })

    # Crear un DataFrame para mostrar los resultados
    df_resultados = pd.DataFrame(resultados)
    return df_resultados

# Ejemplo de uso
if __name__ == "__main__":
    # Parámetros constantes
    MP = 50  # Cantidad total de material inicial en gramos
    pH = 2  # Valor de pH
    tiempo = 2  # Tiempo en horas
    temperatura = 40  # Temperatura en °C
    lixivliquido = 0.238  # Lixiviante en litros
    Cte3 = 23.7  # Residuo sólido seco en gramos
    lavado_l = 0.2020 # Volumen Licor de lavado en litros

    # Parámetros variables
    Composicion = [2.46, 21.70,2.14, 15.40, 1.57]  # Porcentajes de materias primas
    RSS_porcentajes = [0.68,20.4,1,3.09,2.91]  # Porcentajes de residuos sólidos secos
    MPiLL_g_l = [1.12,6.27,0.6,11.1,0.042]  # Licor lavado (g/L)
    cte2_por_MP= [3.3,17.9,2.06,31.7,0.138] #cte2 (g/l)

   # Calcular resultados
resultados12 = calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2_por_MP, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l)
df_resultados12 = pd.DataFrame(resultados12)

df_resultados12.head(5)

  Materia Prima  MP(gr)  Residuo (gr)  Eficacia (BS)  Eficacia (BL)
0            Mg   1.230       0.16116          86.90          82.25
1            Mn  10.850       4.83480          55.44          50.94
2            Al   1.070       0.23700          77.85          57.15
3            Zn   7.700       0.73233          90.49         127.10
4            Fe   0.785       0.68967          12.14           5.26

In [135]:
new_columns12 = pd.DataFrame({
    'MP': [50,50,50,50,50],
    'Ph': [2,2,2,2,2],
    'Tiempo': [2 ,2 ,2 ,2 ,2 ],
    'Temperatura':[40,40,40,40,40],
    'LixivLiqui': [0.238,0.238,0.238,0.238,0.238],
    'Cte3': [23.7,23.7,23.7,23.7,23.7],
    'LicorLavado': [0.2020,0.2020,0.2020,0.2020,0.2020],
})

df12 = pd.concat([df_resultados12,new_columns12], axis=1)
df12.head(5)

,Materia Prima,MP(gr),Residuo (gr),Eficacia (BS),Eficacia (BL),MP,Ph,Tiempo,Temperatura,LixivLiqui,Cte3,LicorLavado
0,Mg,1.230,0.16116,86.90,82.25,50,2,2,40,0.238,23.7,0.202
1,Mn,10.850,4.83480,55.44,50.94,50,2,2,40,0.238,23.7,0.202
2,Al,1.070,0.23700,77.85,57.15,50,2,2,40,0.238,23.7,0.202
3,Zn,7.700,0.73233,90.49,127.10,50,2,2,40,0.238,23.7,0.202
4,Fe,0.785,0.68967,12.14,5.26,50,2,2,40,0.238,23.7,0.202

### Escenario 13

In [136]:
def calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l):
    """
    Función para calcular distintos escenarios del proceso de lixiviación.
    """
    # Nombres de las materias primas
    materias_primas = ['Mg', 'Mn', 'Al', 'Zn', 'Fe']

    # Inicializar resultados
    resultados = []

    # Cálculos para cada materia prima
    for i, MPi_porcentaje in enumerate(Composicion):
        # Nombre de la materia prima
        MPi = materias_primas[i]

        # Cálculo de la cantidad de MPi en gramos
        MPi_g = MPi_porcentaje * MP / 100

        # Cálculo del residuo sólido seco
        Rsi = Cte3 * RSS_porcentajes[i] / 100

        # Cálculo de la eficacia (Base Sólida)
        eficacia_bs = round(((MPi_g - Rsi) / MPi_g)*100,2)

        # Cálculo de la eficacia (Base Líquida)
        eficacia_bl = round((((cte2_por_MP[i] * lixivliquido) + (lavado_l * MPiLL_g_l[i])) / MPi_g)*100,2)


        # Guardar resultados
        resultados.append({
            'Materia Prima': MPi,
            'MP(gr)': MPi_g,
            'Residuo (gr)': Rsi,
            'Eficacia (BS)': eficacia_bs,
            'Eficacia (BL)': eficacia_bl
        })

    # Crear un DataFrame para mostrar los resultados
    df_resultados = pd.DataFrame(resultados)
    return df_resultados

# Ejemplo de uso
if __name__ == "__main__":
    # Parámetros constantes
    MP = 50  # Cantidad total de material inicial en gramos
    pH = 2  # Valor de pH
    tiempo = 2  # Tiempo en horas
    temperatura = 60  # Temperatura en °C
    lixivliquido = 0.196  # Lixiviante en litros
    Cte3 = 23.5  # Residuo sólido seco en gramos
    lavado_l = 0.2 # Volumen Licor de lavado en litros

    # Parámetros variables
    Composicion = [2.46, 21.70,2.14, 15.40, 1.57]  # Porcentajes de materias primas
    RSS_porcentajes = [0.55,20,1.09,3.08,3.1]  # Porcentajes de residuos sólidos secos
    MPiLL_g_l = [0.687,4.03,0.372,6.75,0.018]  # Licor lavado (g/L)
    cte2_por_MP= [4.42,25.5,2.49,44.1,0.123] #cte2 (g/l)

   # Calcular resultados
resultados13 = calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2_por_MP, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l)
df_resultados13 = pd.DataFrame(resultados13)

df_resultados13.head(5)

  Materia Prima  MP(gr)  Residuo (gr)  Eficacia (BS)  Eficacia (BL)
0            Mg   1.230       0.12925          89.49          81.60
1            Mn  10.850       4.70000          56.68          53.49
2            Al   1.070       0.25615          76.06          52.56
3            Zn   7.700       0.72380          90.60         129.79
4            Fe   0.785       0.72850           7.20           3.53

In [137]:
new_columns13 = pd.DataFrame({
    'MP': [50,50,50,50,50],
    'Ph': [2,2,2,2,2],
    'Tiempo': [2 ,2 ,2 ,2 ,2 ],
    'Temperatura':[60,60,60,60,60],
    'LixivLiqui': [0.196,0.196,0.196,0.196,0.196],
    'Cte3': [23.5,23.5,23.5,23.5,23.5],
    'LicorLavado': [0.2,0.2,0.2,0.2,0.2],
})

df13 = pd.concat([df_resultados13,new_columns13], axis=1)
df13.head(5)

,Materia Prima,MP(gr),Residuo (gr),Eficacia (BS),Eficacia (BL),MP,Ph,Tiempo,Temperatura,LixivLiqui,Cte3,LicorLavado
0,Mg,1.230,0.12925,89.49,81.60,50,2,2,60,0.196,23.5,0.2
1,Mn,10.850,4.70000,56.68,53.49,50,2,2,60,0.196,23.5,0.2
2,Al,1.070,0.25615,76.06,52.56,50,2,2,60,0.196,23.5,0.2
3,Zn,7.700,0.72380,90.60,129.79,50,2,2,60,0.196,23.5,0.2
4,Fe,0.785,0.72850,7.20,3.53,50,2,2,60,0.196,23.5,0.2

### Escenario 14

In [138]:
def calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l):
    """
    Función para calcular distintos escenarios del proceso de lixiviación.
    """
    # Nombres de las materias primas
    materias_primas = ['Mg', 'Mn', 'Al', 'Zn', 'Fe']

    # Inicializar resultados
    resultados = []

    # Cálculos para cada materia prima
    for i, MPi_porcentaje in enumerate(Composicion):
        # Nombre de la materia prima
        MPi = materias_primas[i]

        # Cálculo de la cantidad de MPi en gramos
        MPi_g = MPi_porcentaje * MP / 100

        # Cálculo del residuo sólido seco
        Rsi = Cte3 * RSS_porcentajes[i] / 100

        # Cálculo de la eficacia (Base Sólida)
        eficacia_bs = round(((MPi_g - Rsi) / MPi_g)*100,2)

        # Cálculo de la eficacia (Base Líquida)
        eficacia_bl = round((((cte2_por_MP[i] * lixivliquido) + (lavado_l * MPiLL_g_l[i])) / MPi_g)*100,2)


        # Guardar resultados
        resultados.append({
            'Materia Prima': MPi,
            'MP(gr)': MPi_g,
            'Residuo (gr)': Rsi,
            'Eficacia (BS)': eficacia_bs,
            'Eficacia (BL)': eficacia_bl
        })

    # Crear un DataFrame para mostrar los resultados
    df_resultados = pd.DataFrame(resultados)
    return df_resultados

# Ejemplo de uso
if __name__ == "__main__":
    # Parámetros constantes
    MP = 50  # Cantidad total de material inicial en gramos
    pH = 3  # Valor de pH
    tiempo = 1  # Tiempo en horas
    temperatura =40  # Temperatura en °C
    lixivliquido = 0.217  # Lixiviante en litros
    Cte3 = 29.2  # Residuo sólido seco en gramos
    lavado_l = 0.2050 # Volumen Licor de lavado en litros

    # Parámetros variables
    Composicion = [2.46, 21.70,2.14, 15.40, 1.57]  # Porcentajes de materias primas
    RSS_porcentajes = [1.23,23.70,1.29,7.70,2.67]  # Porcentajes de residuos sólidos secos
    MPiLL_g_l = [1.05,4.96,0.44,13,0.003]  # Licor lavado (g/L)
    cte2_por_MP= [2.68,12.6,1.42,38.7,0.01] #cte2 (g/l)

   # Calcular resultados
resultados14 = calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2_por_MP, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l)
df_resultados14 = pd.DataFrame(resultados14)

df_resultados14.head(5)

  Materia Prima  MP(gr)  Residuo (gr)  Eficacia (BS)  Eficacia (BL)
0            Mg   1.230       0.35916          70.80          64.78
1            Mn  10.850       6.92040          36.22          34.57
2            Al   1.070       0.37668          64.80          37.23
3            Zn   7.700       2.24840          70.80         143.67
4            Fe   0.785       0.77964           0.68           0.35

In [139]:
new_columns14 = pd.DataFrame({
    'MP': [50,50,50,50,50],
    'Ph': [3,3,3,3,3],
    'Tiempo': [1,1,1,1,1 ],
    'Temperatura':[40,40,40,40,40],
    'LixivLiqui': [0.217,0.217,0.217,0.217,0.217],
    'Cte3': [29.2,29.2,29.2,29.2,29.2],
    'LicorLavado': [0.205,0.205,0.205,0.205,0.205],
})

df14 = pd.concat([df_resultados14,new_columns14], axis=1)
df14.head(5)

,Materia Prima,MP(gr),Residuo (gr),Eficacia (BS),Eficacia (BL),MP,Ph,Tiempo,Temperatura,LixivLiqui,Cte3,LicorLavado
0,Mg,1.230,0.35916,70.80,64.78,50,3,1,40,0.217,29.2,0.205
1,Mn,10.850,6.92040,36.22,34.57,50,3,1,40,0.217,29.2,0.205
2,Al,1.070,0.37668,64.80,37.23,50,3,1,40,0.217,29.2,0.205
3,Zn,7.700,2.24840,70.80,143.67,50,3,1,40,0.217,29.2,0.205
4,Fe,0.785,0.77964,0.68,0.35,50,3,1,40,0.217,29.2,0.205

### Escenario 15

In [140]:
def calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l):
    """
    Función para calcular distintos escenarios del proceso de lixiviación.
    """
    # Nombres de las materias primas
    materias_primas = ['Mg', 'Mn', 'Al', 'Zn', 'Fe']

    # Inicializar resultados
    resultados = []

    # Cálculos para cada materia prima
    for i, MPi_porcentaje in enumerate(Composicion):
        # Nombre de la materia prima
        MPi = materias_primas[i]

        # Cálculo de la cantidad de MPi en gramos
        MPi_g = MPi_porcentaje * MP / 100

        # Cálculo del residuo sólido seco
        Rsi = Cte3 * RSS_porcentajes[i] / 100

        # Cálculo de la eficacia (Base Sólida)
        eficacia_bs = round(((MPi_g - Rsi) / MPi_g)*100,2)

        # Cálculo de la eficacia (Base Líquida)
        eficacia_bl = round((((cte2_por_MP[i] * lixivliquido) + (lavado_l * MPiLL_g_l[i])) / MPi_g)*100,2)


        # Guardar resultados
        resultados.append({
            'Materia Prima': MPi,
            'MP(gr)': MPi_g,
            'Residuo (gr)': Rsi,
            'Eficacia (BS)': eficacia_bs,
            'Eficacia (BL)': eficacia_bl
        })

    # Crear un DataFrame para mostrar los resultados
    df_resultados = pd.DataFrame(resultados)
    return df_resultados

# Ejemplo de uso
if __name__ == "__main__":
    # Parámetros constantes
    MP = 50  # Cantidad total de material inicial en gramos
    pH = 3  # Valor de pH
    tiempo = 2  # Tiempo en horas
    temperatura =40  # Temperatura en °C
    lixivliquido = 0.218  # Lixiviante en litros
    Cte3 = 28.9  # Residuo sólido seco en gramos
    lavado_l = 0.2020 # Volumen Licor de lavado en litros

    # Parámetros variables
    Composicion = [2.46, 21.70,2.14, 15.40, 1.57]  # Porcentajes de materias primas
    RSS_porcentajes = [0.96,20.20,1.62,2.56,2.52]  # Porcentajes de residuos sólidos secos
    MPiLL_g_l = [0.823,3.86,0.345,8.78,0.003]  # Licor lavado (g/L)
    cte2_por_MP= [2.84,12.5,1.25,30,0.007] #cte2 (g/l)

   # Calcular resultados
resultados15 = calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2_por_MP, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l)
df_resultados15 = pd.DataFrame(resultados15)

df_resultados15.head(5)

  Materia Prima  MP(gr)  Residuo (gr)  Eficacia (BS)  Eficacia (BL)
0            Mg   1.230       0.27744          77.44          63.85
1            Mn  10.850       5.83780          46.20          32.30
2            Al   1.070       0.46818          56.24          31.98
3            Zn   7.700       0.73984          90.39         107.97
4            Fe   0.785       0.72828           7.23           0.27

In [141]:
new_columns15 = pd.DataFrame({
    'MP': [50,50,50,50,50],
    'Ph': [3,3,3,3,3],
    'Tiempo': [2,2,2,2,2 ],
    'Temperatura':[40,40,40,40,40],
    'LixivLiqui': [0.218,0.218,0.218,0.218,0.218],
    'Cte3': [28.9,28.9,28.9,28.9,28.9],
    'LicorLavado': [ 0.2020, 0.2020, 0.2020, 0.2020, 0.2020],
})

df15 = pd.concat([df_resultados15,new_columns15], axis=1)
df15.head(5)

,Materia Prima,MP(gr),Residuo (gr),Eficacia (BS),Eficacia (BL),MP,Ph,Tiempo,Temperatura,LixivLiqui,Cte3,LicorLavado
0,Mg,1.230,0.27744,77.44,63.85,50,3,2,40,0.218,28.9,0.202
1,Mn,10.850,5.83780,46.20,32.30,50,3,2,40,0.218,28.9,0.202
2,Al,1.070,0.46818,56.24,31.98,50,3,2,40,0.218,28.9,0.202
3,Zn,7.700,0.73984,90.39,107.97,50,3,2,40,0.218,28.9,0.202
4,Fe,0.785,0.72828,7.23,0.27,50,3,2,40,0.218,28.9,0.202

### Escenario 16

In [142]:
def calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l):
    """
    Función para calcular distintos escenarios del proceso de lixiviación.
    """
    # Nombres de las materias primas
    materias_primas = ['Mg', 'Mn', 'Al', 'Zn', 'Fe']

    # Inicializar resultados
    resultados = []

    # Cálculos para cada materia prima
    for i, MPi_porcentaje in enumerate(Composicion):
        # Nombre de la materia prima
        MPi = materias_primas[i]

        # Cálculo de la cantidad de MPi en gramos
        MPi_g = MPi_porcentaje * MP / 100

        # Cálculo del residuo sólido seco
        Rsi = Cte3 * RSS_porcentajes[i] / 100

        # Cálculo de la eficacia (Base Sólida)
        eficacia_bs = round(((MPi_g - Rsi) / MPi_g)*100,2)

        # Cálculo de la eficacia (Base Líquida)
        eficacia_bl = round((((cte2_por_MP[i] * lixivliquido) + (lavado_l * MPiLL_g_l[i])) / MPi_g)*100,2)


        # Guardar resultados
        resultados.append({
            'Materia Prima': MPi,
            'MP(gr)': MPi_g,
            'Residuo (gr)': Rsi,
            'Eficacia (BS)': eficacia_bs,
            'Eficacia (BL)': eficacia_bl
        })

    # Crear un DataFrame para mostrar los resultados
    df_resultados = pd.DataFrame(resultados)
    return df_resultados

# Ejemplo de uso
if __name__ == "__main__":
    # Parámetros constantes
    MP = 50  # Cantidad total de material inicial en gramos
    pH = 3  # Valor de pH
    tiempo = 1  # Tiempo en horas
    temperatura =60  # Temperatura en °C
    lixivliquido = 0.188  # Lixiviante en litros
    Cte3 = 33 # Residuo sólido seco en gramos
    lavado_l = 0.2 # Volumen Licor de lavado en litros

    # Parámetros variables
    Composicion = [2.46, 21.70,2.14, 15.40, 1.57]  # Porcentajes de materias primas
    RSS_porcentajes = [1.32,21.3,2.01,8.20,2.23]  # Porcentajes de residuos sólidos secos
    MPiLL_g_l = [1.47,3.43,0.186,8.65,0.003]  # Licor lavado (g/L)
    cte2_por_MP= [2.59,1.19,0.71,30.6,0.003] #cte2 (g/l)

   # Calcular resultados
resultados16 = calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2_por_MP, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l)
df_resultados16 = pd.DataFrame(resultados16)

df_resultados16.head(5)

  Materia Prima  MP(gr)  Residuo (gr)  Eficacia (BS)  Eficacia (BL)
0            Mg   1.230        0.4356          64.59          63.49
1            Mn  10.850        7.0290          35.22           8.38
2            Al   1.070        0.6633          38.01          15.95
3            Zn   7.700        2.7060          64.86          97.18
4            Fe   0.785        0.7359           6.25           0.15

In [143]:
new_columns16 = pd.DataFrame({
    'MP': [50,50,50,50,50],
    'Ph': [3,3,3,3,3],
    'Tiempo': [1,1,1,1,1],
    'Temperatura':[60,60,60,60,60],
    'LixivLiqui': [0.188,0.188,0.188,0.188,0.188],
    'Cte3': [33,33,33,33,33],
    'LicorLavado': [ 0.2,0.2,0.2,0.2,0.2],
})

df16 = pd.concat([df_resultados16,new_columns16], axis=1)
df16.head(5)

,Materia Prima,MP(gr),Residuo (gr),Eficacia (BS),Eficacia (BL),MP,Ph,Tiempo,Temperatura,LixivLiqui,Cte3,LicorLavado
0,Mg,1.230,0.4356,64.59,63.49,50,3,1,60,0.188,33,0.2
1,Mn,10.850,7.0290,35.22,8.38,50,3,1,60,0.188,33,0.2
2,Al,1.070,0.6633,38.01,15.95,50,3,1,60,0.188,33,0.2
3,Zn,7.700,2.7060,64.86,97.18,50,3,1,60,0.188,33,0.2
4,Fe,0.785,0.7359,6.25,0.15,50,3,1,60,0.188,33,0.2

### Escenario 17

In [144]:
def calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l):
    """
    Función para calcular distintos escenarios del proceso de lixiviación.
    """
    # Nombres de las materias primas
    materias_primas = ['Mg', 'Mn', 'Al', 'Zn', 'Fe']

    # Inicializar resultados
    resultados = []

    # Cálculos para cada materia prima
    for i, MPi_porcentaje in enumerate(Composicion):
        # Nombre de la materia prima
        MPi = materias_primas[i]

        # Cálculo de la cantidad de MPi en gramos
        MPi_g = MPi_porcentaje * MP / 100

        # Cálculo del residuo sólido seco
        Rsi = Cte3 * RSS_porcentajes[i] / 100

        # Cálculo de la eficacia (Base Sólida)
        eficacia_bs = round(((MPi_g - Rsi) / MPi_g)*100,2)

        # Cálculo de la eficacia (Base Líquida)
        eficacia_bl = round((((cte2_por_MP[i] * lixivliquido) + (lavado_l * MPiLL_g_l[i])) / MPi_g)*100,2)


        # Guardar resultados
        resultados.append({
            'Materia Prima': MPi,
            'MP(gr)': MPi_g,
            'Residuo (gr)': Rsi,
            'Eficacia (BS)': eficacia_bs,
            'Eficacia (BL)': eficacia_bl
        })

    # Crear un DataFrame para mostrar los resultados
    df_resultados = pd.DataFrame(resultados)
    return df_resultados

# Ejemplo de uso
if __name__ == "__main__":
    # Parámetros constantes
    MP = 50  # Cantidad total de material inicial en gramos
    pH = 3  # Valor de pH
    tiempo = 2  # Tiempo en horas
    temperatura =60  # Temperatura en °C
    lixivliquido = 0.225  # Lixiviante en litros
    Cte3 = 35.9 # Residuo sólido seco en gramos
    lavado_l = 0.2020 # Volumen Licor de lavado en litros

    # Parámetros variables
    Composicion = [2.46, 21.70,2.14, 15.40, 1.57]  # Porcentajes de materias primas
    RSS_porcentajes = [1.08,16.8,2.47,2.6,2.11]  # Porcentajes de residuos sólidos secos
    MPiLL_g_l = [0.504,2.21,0.037,3.18,0.003]  # Licor lavado (g/L)
    cte2_por_MP= [3.19,13.9,0.396,20.2,0.003] #cte2 (g/l)

   # Calcular resultados
resultados17 = calcular_escenarios(MP, Composicion, pH, tiempo, temperatura, lixivliquido, cte2_por_MP, Cte3, RSS_porcentajes, lavado_l, MPiLL_g_l)
df_resultados17 = pd.DataFrame(resultados17)

df_resultados17.head(5)

  Materia Prima  MP(gr)  Residuo (gr)  Eficacia (BS)  Eficacia (BL)
0            Mg   1.230       0.38772          68.48          66.63
1            Mn  10.850       6.03120          44.41          32.94
2            Al   1.070       0.88673          17.13           9.03
3            Zn   7.700       0.93340          87.88          67.37
4            Fe   0.785       0.75749           3.50           0.16

In [145]:
new_columns17 = pd.DataFrame({
    'MP': [50,50,50,50,50],
    'Ph': [3,3,3,3,3],
    'Tiempo': [2,2,2,2,2],
    'Temperatura':[60,60,60,60,60],
    'LixivLiqui': [0.225,0.225,0.225,0.225,0.225],
    'Cte3': [35.9 ,35.9 ,35.9 ,35.9 ,35.9],
    'LicorLavado': [ 0.2020,0.2020,0.2020,0.2020,0.2020],
})

df17 = pd.concat([df_resultados17,new_columns17], axis=1)
df17.head(5)

,Materia Prima,MP(gr),Residuo (gr),Eficacia (BS),Eficacia (BL),MP,Ph,Tiempo,Temperatura,LixivLiqui,Cte3,LicorLavado
0,Mg,1.230,0.38772,68.48,66.63,50,3,2,60,0.225,35.9,0.202
1,Mn,10.850,6.03120,44.41,32.94,50,3,2,60,0.225,35.9,0.202
2,Al,1.070,0.88673,17.13,9.03,50,3,2,60,0.225,35.9,0.202
3,Zn,7.700,0.93340,87.88,67.37,50,3,2,60,0.225,35.9,0.202
4,Fe,0.785,0.75749,3.50,0.16,50,3,2,60,0.225,35.9,0.202

### CONCATENACION DFs

In [146]:
#lista de dataframes
dataframes=[df,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16,df17]
# Concatenar en un único DataFrame
master = pd.concat(dataframes, ignore_index=True)
# Mostrar el DataFrame consolidado
master.head(20)

,Materia Prima,MP(gr),Residuo (gr),Eficacia (BS),Eficacia (BL),MP,Ph,Tiempo,Temperatura,LixivLiqui,Cte3,LicorLavado
0,Mg,1.230,0.07684,93.75,74.63,50,0.5,1,40,0.294,22.6,0.218
1,Mn,10.850,3.32220,69.38,53.22,50,0.5,1,40,0.294,22.6,0.218
2,Al,1.070,0.19210,82.05,62.29,50,0.5,1,40,0.294,22.6,0.218
3,Zn,7.700,0.25990,96.62,124.68,50,0.5,1,40,0.294,22.6,0.218
4,Fe,0.785,0.44748,43.00,35.32,50,0.5,1,40,0.294,22.6,0.218
5,Mg,1.230,0.05300,95.69,82.32,50,0.5,1,60,0.400,21.2,0.218
6,Mn,10.850,2.50160,76.94,63.91,50,0.5,1,60,0.400,21.2,0.218
7,Al,1.070,0.23956,77.61,71.83,50,0.5,1,60,0.400,21.2,0.218
8,Zn,7.700,0.25652,96.67,137.46,50,0.5,1,60,0.400,21.2,0.218
9,Fe,0.785,0.29256,62.73,53.38,50,0.5,1,60,0.400,21.2,0.218
10,Mg,1.230,0.04708,96.17,77.62,50,0.5,2,40,0.400,21.2,0.218
11,Mn,10.850,2.93180,72.98,56.31,50,0.5,2,40,0.400,21.2,0.218
12,Al,1.070,0.15836,85.20,61.58,50,0.5,2,40,0.400,21.2,0.218
13,Zn,7.700,0.18190,97.64,122.66,50,0.5,2,40,0.400,21.2,0.218
14,Fe,0.785,0.43656,44.39,49.61,50,0.5,2,40,0.400,21.2,0.218
15,Mg,1.230,0.06448,94.76,79.97,50,0.5,2,40,0.400,20.8,0.335
16,Mn,10.850,3.70240,65.88,58.37,50,0.5,2,40,0.400,20.8,0.335
17,Al,1.070,0.18928,82.31,60.28,50,0.5,2,40,0.400,20.8,0.335
18,Zn,7.700,0.24336,96.84,138.72,50,0.5,2,40,0.400,20.8,0.335
19,Fe,0.785,0.50752,35.35,32.12,50,0.5,2,40,0.400,20.8,0.335

In [147]:
# Define a function to calculate acid concentration from pH
def calculate_acid_concentration(ph):
    return 10 ** (-ph)

# Apply the function to calculate acid concentration for each row
master['Acid Concentration'] = master['Ph'].apply(calculate_acid_concentration)

# Save updated dataframe
#file_path = "updated_master.xlsx"
#master.to_excel(file_path, index=False)

#print("Acid concentration calculated and saved to updated_master.xlsx.")
master.head()

,Materia Prima,MP(gr),Residuo (gr),Eficacia (BS),Eficacia (BL),MP,Ph,Tiempo,Temperatura,LixivLiqui,Cte3,LicorLavado,Acid Concentration
0,Mg,1.230,0.07684,93.75,74.63,50,0.5,1,40,0.294,22.6,0.218,0.316228
1,Mn,10.850,3.32220,69.38,53.22,50,0.5,1,40,0.294,22.6,0.218,0.316228
2,Al,1.070,0.19210,82.05,62.29,50,0.5,1,40,0.294,22.6,0.218,0.316228
3,Zn,7.700,0.25990,96.62,124.68,50,0.5,1,40,0.294,22.6,0.218,0.316228
4,Fe,0.785,0.44748,43.00,35.32,50,0.5,1,40,0.294,22.6,0.218,0.316228

In [148]:
# Define a fixed pulp density value
pulp_density = 200  # in g/L

# Calculate the Volume of Acid (L) and add it to the DataFrame
master['Volume of Acid (L)'] = master['MP(gr)'] / pulp_density

In [149]:
master.head()

,Materia Prima,MP(gr),Residuo (gr),Eficacia (BS),Eficacia (BL),MP,Ph,Tiempo,Temperatura,LixivLiqui,Cte3,LicorLavado,Acid Concentration,Volume of Acid (L)
0,Mg,1.230,0.07684,93.75,74.63,50,0.5,1,40,0.294,22.6,0.218,0.316228,0.006150
1,Mn,10.850,3.32220,69.38,53.22,50,0.5,1,40,0.294,22.6,0.218,0.316228,0.054250
2,Al,1.070,0.19210,82.05,62.29,50,0.5,1,40,0.294,22.6,0.218,0.316228,0.005350
3,Zn,7.700,0.25990,96.62,124.68,50,0.5,1,40,0.294,22.6,0.218,0.316228,0.038500
4,Fe,0.785,0.44748,43.00,35.32,50,0.5,1,40,0.294,22.6,0.218,0.316228,0.003925

In [150]:
master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Materia Prima       85 non-null     object
 1   MP(gr)              85 non-null     float64
 2   Residuo (gr)        85 non-null     float64
 3   Eficacia (BS)       85 non-null     float64
 4   Eficacia (BL)       85 non-null     float64
 5   MP                  85 non-null     int64
 6   Ph                  85 non-null     float64
 7   Tiempo              85 non-null     int64
 8   Temperatura         85 non-null     int64
 9   LixivLiqui          85 non-null     float64
 10  Cte3                85 non-null     float64
 11  LicorLavado         85 non-null     float64
 12  Acid Concentration  85 non-null     float64
 13  Volume of Acid (L)  85 non-null     float64
dtypes: float64(10), int64(3), object(1)
memory usage: 9.4+ KB

In [151]:
master.describe()

,MP(gr),Residuo (gr),Eficacia (BS),Eficacia (BL),MP,Ph,Tiempo,Temperatura,LixivLiqui,Cte3,LicorLavado,Acid Concentration,Volume of Acid (L)
count,85.000000,85.000000,85.000000,85.000000,85.0,85.000000,85.000000,85.000000,85.000000,85.000000,85.000000,85.000000,85.000000
mean,4.327000,1.239973,66.700941,65.231647,50.0,1.558824,1.529412,49.411765,0.270588,24.847059,0.218765,0.119126,0.021635
std,4.188166,1.771043,27.899455,37.628611,0.0,0.974104,0.502096,10.041929,0.074049,4.701712,0.043431,0.133443,0.020941
min,0.785000,0.040470,0.680000,0.150000,50.0,0.500000,1.000000,40.000000,0.188000,18.900000,0.190000,0.001000,0.003925
25%,1.070000,0.210240,50.730000,38.320000,50.0,0.500000,1.000000,40.000000,0.217000,21.300000,0.200000,0.010000,0.005350
50%,1.230000,0.436560,73.440000,63.810000,50.0,1.000000,2.000000,40.000000,0.238000,23.500000,0.202000,0.100000,0.006150
75%,7.700000,0.933400,89.490000,82.250000,50.0,2.000000,2.000000,60.000000,0.330000,28.900000,0.218000,0.316228,0.038500
max,10.850000,7.029000,98.560000,143.670000,50.0,3.000000,2.000000,60.000000,0.400000,35.900000,0.335000,0.316228,0.054250

In [152]:
master.isna().sum()

Materia Prima         0
MP(gr)                0
Residuo (gr)          0
Eficacia (BS)         0
Eficacia (BL)         0
MP                    0
Ph                    0
Tiempo                0
Temperatura           0
LixivLiqui            0
Cte3                  0
LicorLavado           0
Acid Concentration    0
Volume of Acid (L)    0
dtype: int64

In [153]:
master.head(20)

,Materia Prima,MP(gr),Residuo (gr),Eficacia (BS),Eficacia (BL),MP,Ph,Tiempo,Temperatura,LixivLiqui,Cte3,LicorLavado,Acid Concentration,Volume of Acid (L)
0,Mg,1.230,0.07684,93.75,74.63,50,0.5,1,40,0.294,22.6,0.218,0.316228,0.006150
1,Mn,10.850,3.32220,69.38,53.22,50,0.5,1,40,0.294,22.6,0.218,0.316228,0.054250
2,Al,1.070,0.19210,82.05,62.29,50,0.5,1,40,0.294,22.6,0.218,0.316228,0.005350
3,Zn,7.700,0.25990,96.62,124.68,50,0.5,1,40,0.294,22.6,0.218,0.316228,0.038500
4,Fe,0.785,0.44748,43.00,35.32,50,0.5,1,40,0.294,22.6,0.218,0.316228,0.003925
5,Mg,1.230,0.05300,95.69,82.32,50,0.5,1,60,0.400,21.2,0.218,0.316228,0.006150
6,Mn,10.850,2.50160,76.94,63.91,50,0.5,1,60,0.400,21.2,0.218,0.316228,0.054250
7,Al,1.070,0.23956,77.61,71.83,50,0.5,1,60,0.400,21.2,0.218,0.316228,0.005350
8,Zn,7.700,0.25652,96.67,137.46,50,0.5,1,60,0.400,21.2,0.218,0.316228,0.038500
9,Fe,0.785,0.29256,62.73,53.38,50,0.5,1,60,0.400,21.2,0.218,0.316228,0.003925
10,Mg,1.230,0.04708,96.17,77.62,50,0.5,2,40,0.400,21.2,0.218,0.316228,0.006150
11,Mn,10.850,2.93180,72.98,56.31,50,0.5,2,40,0.400,21.2,0.218,0.316228,0.054250
12,Al,1.070,0.15836,85.20,61.58,50,0.5,2,40,0.400,21.2,0.218,0.316228,0.005350
13,Zn,7.700,0.18190,97.64,122.66,50,0.5,2,40,0.400,21.2,0.218,0.316228,0.038500
14,Fe,0.785,0.43656,44.39,49.61,50,0.5,2,40,0.400,21.2,0.218,0.316228,0.003925
15,Mg,1.230,0.06448,94.76,79.97,50,0.5,2,40,0.400,20.8,0.335,0.316228,0.006150
16,Mn,10.850,3.70240,65.88,58.37,50,0.5,2,40,0.400,20.8,0.335,0.316228,0.054250
17,Al,1.070,0.18928,82.31,60.28,50,0.5,2,40,0.400,20.8,0.335,0.316228,0.005350
18,Zn,7.700,0.24336,96.84,138.72,50,0.5,2,40,0.400,20.8,0.335,0.316228,0.038500
19,Fe,0.785,0.50752,35.35,32.12,50,0.5,2,40,0.400,20.8,0.335,0.316228,0.003925

In [154]:
rename_columns ={
    "Materia Prima" : "Metal",
    "MP" : "Cantidad Total(gr)",
    "LixivLiqui": "Disolvente",
    "Acid Concentration": "Concentración de ácido",
    "Volume of Acid (L)": "Volúmen de ácido (L)"
    
}

In [155]:
master.rename(columns=rename_columns, inplace=True)

In [156]:
master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Metal                   85 non-null     object
 1   MP(gr)                  85 non-null     float64
 2   Residuo (gr)            85 non-null     float64
 3   Eficacia (BS)           85 non-null     float64
 4   Eficacia (BL)           85 non-null     float64
 5   Cantidad Total(gr)      85 non-null     int64
 6   Ph                      85 non-null     float64
 7   Tiempo                  85 non-null     int64
 8   Temperatura             85 non-null     int64
 9   Disolvente              85 non-null     float64
 10  Cte3                    85 non-null     float64
 11  LicorLavado             85 non-null     float64
 12  Concentración de ácido  85 non-null     float64
 13  Volúmen de ácido (L)    85 non-null     float64
dtypes: float64(10), int64(3), object(1)
memory usage: 9.4+ KB

#### Save results in an excel

In [157]:
#save results in an excel files
file_path="master_updated.xlsx"
master.to_excel(file_path, index=False)